const SANITY_DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production"
const SANITY_PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "j9ou61ca"
const SANITY_API_VERSION = process.env.NEXT_PUBLIC_SANITY_API_VERSION ?? "2025-04-17"

const SANITY_API_TOKEN = process.env.SANITY_API_TOKEN ?? ""

const API_MOCKING = process.env.NEXT_PUBLIC_API_MOCKING ?? "disabled"

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://enheqlnywwgrpouprkxz.supabase.co"
const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaGVxbG55d3dncnBvdXBya3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODU1NTYsImV4cCI6MjA2MTg2MTU1Nn0.-lQg4SMLycMJ3dGxuiITliYl56ZxWRkamAAJL7UVTf8"

export {
  SANITY_DATASET,
  SANITY_PROJECT_ID,
  SANITY_API_VERSION,
  SANITY_API_TOKEN,
  API_MOCKING,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
}
