const SANITY_DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production"
const SANITY_PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "j9ou61ca"
const SANITY_API_VERSION = process.env.NEXT_PUBLIC_SANITY_API_VERSION ?? "2025-04-17"

const SANITY_API_TOKEN = process.env.SANITY_API_TOKEN ?? ""

export {SANITY_DATASET, SANITY_PROJECT_ID, SANITY_API_VERSION, SANITY_API_TOKEN}
