name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm dlx playwright install --with-deps

      - name: Turbo Build
        run: pnpm turbo run build

      - name: Turbo Storybook
        run: pnpm turbo run build-storybook

      - name: Turbo Lint
        run: pnpm turbo run lint

      - name: Turbo Typecheck
        run: pnpm turbo run typecheck

      - name: Turbo E2E
        run: pnpm turbo run e2e

      - name: Turbo Unit Tests
        run: pnpm turbo run test
